# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import tic_tac_toe_pb2 as tic__tac__toe__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tic_tac_toe_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GameStub(object):
    """Layanan gRPC
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Play = channel.stream_stream(
                '/tictactoe.Game/Play',
                request_serializer=tic__tac__toe__pb2.ClientMessage.SerializeToString,
                response_deserializer=tic__tac__toe__pb2.ServerMessage.FromString,
                _registered_method=True)


class GameServicer(object):
    """Layanan gRPC
    """

    def Play(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Play': grpc.stream_stream_rpc_method_handler(
                    servicer.Play,
                    request_deserializer=tic__tac__toe__pb2.ClientMessage.FromString,
                    response_serializer=tic__tac__toe__pb2.ServerMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tictactoe.Game', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tictactoe.Game', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Game(object):
    """Layanan gRPC
    """

    @staticmethod
    def Play(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/tictactoe.Game/Play',
            tic__tac__toe__pb2.ClientMessage.SerializeToString,
            tic__tac__toe__pb2.ServerMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
