# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tic_tac_toe.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tic_tac_toe.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11tic_tac_toe.proto\x12\ttictactoe\"\x1b\n\x04Join\x12\x13\n\x0bplayer_name\x18\x01 \x01(\t\".\n\x04Move\x12\x10\n\x08match_id\x18\x01 \x01(\t\x12\t\n\x01x\x18\x02 \x01(\x05\x12\t\n\x01y\x18\x03 \x01(\x05\"\\\n\rClientMessage\x12\x1f\n\x04join\x18\x01 \x01(\x0b\x32\x0f.tictactoe.JoinH\x00\x12\x1f\n\x04move\x18\x02 \x01(\x0b\x32\x0f.tictactoe.MoveH\x00\x42\t\n\x07payload\"W\n\x06Joined\x12\x10\n\x08match_id\x18\x01 \x01(\t\x12\x13\n\x0byour_symbol\x18\x02 \x01(\t\x12\x10\n\x08opponent\x18\x03 \x01(\t\x12\x14\n\x0cstart_player\x18\x04 \x01(\t\"O\n\tGameState\x12\x10\n\x08match_id\x18\x01 \x01(\t\x12\r\n\x05\x62oard\x18\x02 \x03(\t\x12\x11\n\tnext_turn\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\"\x18\n\x05\x45rror\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x87\x01\n\rServerMessage\x12#\n\x06joined\x18\x01 \x01(\x0b\x32\x11.tictactoe.JoinedH\x00\x12%\n\x05state\x18\x02 \x01(\x0b\x32\x14.tictactoe.GameStateH\x00\x12\x1f\n\x03\x65rr\x18\x03 \x01(\x0b\x32\x10.tictactoe.ErrorH\x00\x42\t\n\x07payload2F\n\x04Game\x12>\n\x04Play\x12\x18.tictactoe.ClientMessage\x1a\x18.tictactoe.ServerMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tic_tac_toe_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JOIN']._serialized_start=32
  _globals['_JOIN']._serialized_end=59
  _globals['_MOVE']._serialized_start=61
  _globals['_MOVE']._serialized_end=107
  _globals['_CLIENTMESSAGE']._serialized_start=109
  _globals['_CLIENTMESSAGE']._serialized_end=201
  _globals['_JOINED']._serialized_start=203
  _globals['_JOINED']._serialized_end=290
  _globals['_GAMESTATE']._serialized_start=292
  _globals['_GAMESTATE']._serialized_end=371
  _globals['_ERROR']._serialized_start=373
  _globals['_ERROR']._serialized_end=397
  _globals['_SERVERMESSAGE']._serialized_start=400
  _globals['_SERVERMESSAGE']._serialized_end=535
  _globals['_GAME']._serialized_start=537
  _globals['_GAME']._serialized_end=607
# @@protoc_insertion_point(module_scope)
